# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: contra1234
      MYSQL_DATABASE: inventario
    networks:
      - backend
    volumes:
      - ./data:/var/lib/mysql
  apirest:
    image: apinest
    networks:
      - backend
    links: 
      - "db:mysql"
networks:
  backend:
    driver: bridge
